### ISSUE TITLE
Impact assessment for replacing redis with valkey

### ISSUE THREAD

**Issue by Sandy-at-Tazama** [tazama-lf/tazama-project#41]
## Acceptance criteria

 - list of services

**Comment by cshezi** [comment]
### **Impact Assessment Report**

During testing, Tazama was fully evaluated with Valkey (version 7.2.5) as a replacement for Redis. Redis was removed entirely, and Tazama continued to operate without issues. We monitored Tazama’s transactions with Valkey and confirmed that each processor was able to interact with Valkey in a similar manner to Redis, with no apparent disruptions.

In the process of replacing Redis with Valkey, we identified three possible approaches:

1. **Environment-Based Change**  
   - Point the platform to the Valkey cache system directly by removing Redis and using the Valkey image. Configure the default port to match Redis’s port to streamline the transition.

2. **Code Modification: Generic Class Rename**  
   - Refactor the code to rename Redis-related classes to Valkey or a more generic name, such as `DistributedCache`, for flexibility.

3. **Code Modification: Separate Class for Valkey**  
   - Add a dedicated class for Valkey within `frms-coe-lib`, enabling both Redis and Valkey to be supported as distinct caching options.

The team’s preference is the **first approach** (Environment-Based Change), as it simplifies the transition without requiring major code changes. This approach would primarily impact the following repositories:

- EKS (Elastic Kubernetes Service)
- AKS (Azure Kubernetes Service)
- Tazama-full-stack-docker
